apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: italy
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: mongo
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: password
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 75m
            memory: 150Mi
          limits:
            cpu: 200m
            memory: 1Gi
        volumeMounts:
        - mountPath: "/data/db"
          name: task-pv-storage
        
