apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: belgium
  labels:
    app: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: infectieradarbe/web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 350Mi
