apiVersion: v1
kind: Service
metadata:
  name: email-client-service
  namespace: belgium
spec:
  type: NodePort
  selector:
    app: email-client
  ports:
  - name: grpc
    port: 5005
    protocol: TCP
    targetPort: 5005
  - name: smtpssl-svc
    port: 465
    protocol: TCP
    targetPort: 465
  - name: smtpauth-svc
    port: 587
    protocol: TCP
    targetPort: 587
