apiVersion: v1
kind: Service
metadata:
  name: messaging-scheduler-service
  namespace: belgium
spec:
  type: ClusterIP
  selector:
    app: message-scheduler
  ports:
  - name: grpc
    protocol: TCP
    port: 5009
    targetPort: 5009