apiVersion: v1
kind: Service
metadata:
  name: mongo-atlas-service
  namespace: italy
spec:
  selector:
    app: mongo
  clusterIP: None
  ports:
  - name: grpc
    protocol: TCP
    port: 27017
    targetPort: 27017