apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer }}
spec:
  acme:
    server: {{ .Values.acmeServer }} 
    email: {{ .Values.connectedEmail }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer }}
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: v1    
kind: Secret
metadata:
    name: jwt-collection
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    jwt-key: {{ .Values.jwtKey }}
---
apiVersion: v1    
kind: Secret
metadata:
    name: case-mongodb-atlas
    namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
    username: {{ .Values.mongoUsername }}
    password: {{ .Values.mongoPassword }}
    connectionPrefix: {{ .Values.mongoConnectionPrefix }}
---
apiVersion: v1    
kind: Secret
metadata:
    name: recaptcha-collection
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    recaptchaKey: {{ .Values.googleRecaptchaKey }}
