{{- with .Values.svcMessaging }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec: 
    replicas: {{ .replicas }}
    selector:
      matchLabels:
        app: {{ .name }}
    template:
      metadata:
       labels:
         app: {{ .name }}
      spec:
        containers:
          - name: {{ .name }}
            image: {{ .image }}
            imagePullPolicy: {{ .imagePullPolicy | default "Always" }}
            env:
              - name: MESSAGING_SERVICE_LISTEN_PORT
                value: {{ .containerPort | quote }}
              - name: GLOBAL_DB_CONNECTION_STR
                value: "{{ (tpl $.Values.dbConnectionStr $) }}"
              - name: GLOBAL_DB_CONNECTION_PREFIX
                value: "{{ $.Values.connectionPrefix }}"
              - name: GLOBAL_DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: "{{ $.Values.dbSecretName }}"
                    key: username
              - name: GLOBAL_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "{{ $.Values.dbSecretName }}"
                    key: password
              - name: MESSAGE_DB_CONNECTION_STR
                value: "{{ default .dbConnectionStr (tpl $.Values.dbConnectionStr $) }}"
              - name: MESSAGE_DB_CONNECTION_PREFIX
                value: "{{ default .dbConnectionPrefix $.Values.dbConnectionPrefix }}"
              - name: MESSAGE_DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: "{{ default .dbSecretName $.Values.dbSecretName }}"
                    key: username
              - name: MESSAGE_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "{{ default .dbSecretName $.Values.dbSecretName }}"
                    key: password
              - name: DB_TIMEOUT
                value: "{{ .dbTimeout }}"
              - name: DB_IDLE_CONN_TIMEOUT
                value: "{{ .dbIdleTimeout }}"
              - name: DB_MAX_POOL_SIZE
                value: "8"
              - name: DB_DB_NAME_PREFIX
                value: "{{ $.Values.dbNamePrefix }}"
              - name: ADDR_USER_MANAGEMENT_SERVICE
                value: "{{ template "ref.UserManagement" $ }}"
              - name: ADDR_STUDY_SERVICE
                value: "{{ template "ref.StudyService" $ }}"
              - name: ADDR_EMAIL_CLIENT_SERVICE
                value: "{{ template "ref.emailClientService" $ }}"
              - name: ADDR_LOGGING_SERVICE
                value: "{{ template "ref.loggingService" $ }}"
            ports:
              - containerPort: {{ .containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
  namespace: {{ $.Values.namespace }}
spec: 
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
{{- end }}
