{{- with .Values.svcEmailClient }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas | default 1}}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy | default "Always" }}
          env:
            - name: EMAIL_CLIENT_SERVICE_LISTEN_PORT
              value: {{ .containerPort | quote }}
            - name: MESSAGING_CONFIG_FOLDER
              value: "/config"
          volumeMounts:
            - name: config-volume
              mountPath: /config/
          ports:
            - containerPort: {{ .containerPort }}
              protocol: TCP
            - containerPort: 465
              name: smtpssl
              protocol: TCP
            - containerPort: 587
              name: smtpauth
              protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: {{ .configMapName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
  namespace: {{ $.Values.namespace }}
spec: 
  type: NodePort
  selector:
    app: {{ .name }}
  ports:
    - name: grpc
      port: {{ .containerPort }}
      protocol: TCP
      targetPort: {{ .containerPort }}
    - name: smtpssl-svc
      port: 465
      protocol: TCP
      targetPort: 465
    - name: smtpauth-svc
      port: 587
      protocol: TCP
      targetPort: 587
{{- end }}